import {createRequire} from 'node:module'
import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {join} from 'node:path'

const require=createRequire(import.meta.url)
const root=process.cwd()
const read=p=>readFileSync(join(root,p),'utf8')

test('stock entry is atomic, user-scoped, review-first and not capped at 500 items',()=>{
  const stock=read('components/modules-stock.jsx')
  assert.match(stock,/gh-stock-count-draft:'\+profile\.id|gh-stock-count-draft:\$\{profile\.id\}|draftKey='gh-stock-count-draft:'\+profile\.id/)
  assert.match(stock,/proc_submit_stock_and_continue_v3/)
  assert.match(stock,/proc_begin_stock_count_session_v1/)
  assert.match(stock,/startPromise=useRef\(null\)/)
  assert.doesNotMatch(stock,/proc_submit_stock_and_continue_v2/)
  assert.doesNotMatch(stock,/range\(0,dueOnly\?Math\.max\(dailyTarget-1,0\):499\)/)
  assert.match(stock,/Shortages will go to Procurement Review/)
  assert.match(stock,/Discard Draft/)
})

test('stock submission history preserves prior counts and can be expanded',()=>{
  const stock=read('components/modules-stock.jsx')
  const migration=read('supabase/migrations/049_procurement_four_step_flow.sql')
  const i18n=read('lib/i18n.js')
  assert.match(stock,/Stock Submission History/)
  assert.match(stock,/proc_stock_submission_history_v1/)
  assert.match(stock,/proc_stock_submission_detail_v1/)
  assert.match(i18n,/older submissions stay unchanged/)
  assert.match(migration,/create or replace function public\.proc_stock_submission_history_v1/)
  assert.match(migration,/create or replace function public\.proc_stock_submission_detail_v1/)
  assert.match(migration,/where c\.status='submitted'/)
})

test('routine shortages stop at buyer review instead of auto-awarding',()=>{
  const buying=read('components/modules-buying.jsx')
  const migration=read('supabase/migrations/049_procurement_four_step_flow.sql')
  assert.match(migration,/procurement\.straight_through/)
  assert.match(migration,/enabled=false/)
  assert.match(migration,/manual_review_required/)
  assert.match(migration,/review_required/)
  assert.match(migration,/source_type='stock_count'/)
  assert.match(migration,/caller,'stock_count'/)
  assert.match(migration,/source_type='manual'/)
  assert.match(migration,/source_type='normal' and source_count_line_id is null/)
  assert.match(migration,/then 'quoting'/)
  assert.match(migration,/set selected_for_po=\(new_target>existing_req\.ordered_qty\)/)
  assert.match(migration,/as has_active_rfq/)
  assert.match(buying,/eq\('has_active_rfq',false\)/)
  assert.doesNotMatch(buying,/proc_try_auto_award_v2/)
  assert.match(buying,/Approve & Continue/)
  assert.match(buying,/Step 4 · Review & Choose Suppliers/)
})

test('guided procurement path continues numbering after stock entry',()=>{
  const ui=read('components/ui.jsx')
  const buying=read('components/modules-buying.jsx')
  const docs=read('components/modules-documents.jsx')
  assert.match(ui,/1 ·/)
  assert.match(ui,/2 ·/)
  assert.match(ui,/3 ·/)
  assert.match(ui,/\[4,t\('journey\.review'/)
  assert.match(ui,/\[5,t\('journey\.rfq'/)
  assert.match(ui,/\[6,t\('journey\.quotes'/)
  assert.match(ui,/\[7,t\('journey\.order'/)
  assert.match(buying,/ProcurementPath active=\{4\}/)
  assert.match(buying,/ProcurementPath active=\{journeyStage\}/)
  assert.match(buying,/awardOpen\?7/)
  assert.match(docs,/ProcurementPath active=\{7\}/)
})

test('RFQs are prepared until actual transmission is confirmed',()=>{
  const buying=read('components/modules-buying.jsx')
  const migration=read('supabase/migrations/048_procurement_complete_hardening.sql')
  assert.match(buying,/proc_create_rfq_v4/)
  assert.match(buying,/proc_mark_rfq_supplier_sent_v1/)
  assert.match(buying,/Confirm Sent/)
  assert.match(migration,/values\(rfq_id,rfq_no,'prepared'/)
  assert.match(migration,/status='sent',sent_at=now\(\),sent_by=caller/)
})

test('supplier RFQs can be exported as PDFs before sending',()=>{
  const buying=read('components/modules-buying.jsx')
  const pdf=read('lib/pdf.js')
  assert.match(buying,/exportSupplierPriceRequestPdf/)
  assert.match(buying,/RFQ PDF/)
  assert.match(pdf,/export function exportSupplierPriceRequestPdf/)
  assert.match(pdf,/REQUEST FOR QUOTATION/)
  assert.match(pdf,/Delivery \/ Lead Time/)
})

test('quote OCR cannot reuse one supplier row and no size-only match is accepted',()=>{
  const buying=read('components/modules-buying.jsx')
  assert.match(buying,/usedRows=new Set\(\)/)
  assert.match(buying,/usedRows\.has\(index\)/)
  assert.match(buying,/acceptable:codeExact\|\|descriptionStrong/)
  assert.doesNotMatch(buying,/bestScore>=0\.45/)
})

test('award review is delivery-aware for urgent items and still supports audited overrides',()=>{
  const buying=read('components/modules-buying.jsx')
  const awardMigration=read('supabase/migrations/043_procurement_quote_award_hardening.sql')
  const hardening=read('supabase/migrations/048_procurement_complete_hardening.sql')
  assert.match(buying,/function itemNeedsSpeed/)
  assert.match(buying,/priority==='urgent'\|\|priority==='high'/)
  assert.match(buying,/Faster delivery preferred/)
  assert.match(buying,/recommendedQuoteLine/)
  assert.match(buying,/automaticAwardReason/)
  assert.match(buying,/System recommendation: faster delivery for urgent\/high-priority requirement/)
  assert.match(buying,/System allocation: lower-cost suppliers could not fully cover/)
  assert.match(buying,/override_reason/)
  assert.match(buying,/proc_finalize_award_plan_v2/)
  assert.match(awardMigration,/Choosing a non-recommended supplier requires an override reason/)
  assert.match(hardening,/count\(distinct q\.supplier_id\)/)
  assert.match(hardening,/least\(preferred,greatest\(eligible,1\)\)/)
})

test('landed-cost comparison cannot be diluted by declared availability',()=>{
  const migration=read('supabase/migrations/048_procurement_complete_hardening.sql')
  assert.match(migration,/least\(coalesce\(ql\.available_qty,qi\.requested_qty\),qi\.requested_qty\)/)
  assert.doesNotMatch(migration,/sum\(COALESCE\(ql\.available_qty, qi\.requested_qty\)\)/)
})

test('invoice matching is PO + GRN + invoice and receiving requires rejection reasons',()=>{
  const docs=read('components/modules-documents.jsx')
  const migration=read('supabase/migrations/048_procurement_complete_hardening.sql')
  assert.match(docs,/proc_create_invoice_v4/)
  assert.match(docs,/Already Invoiced/)
  assert.match(docs,/Invoiceable/)
  assert.match(migration,/available_to_invoice:=greatest\(accepted_to_date-previously_invoiced,0\)/)
  assert.match(migration,/proc_v_invoiceable_po_lines/)
  assert.match(docs,/invoiceLines=lines\.filter/)
  assert.match(migration,/A rejection reason is required/)
})

test('health check reports commit and database readiness',()=>{
  const route=read('app/api/health/route.ts')
  assert.match(route,/VERCEL_GIT_COMMIT_SHA/)
  assert.match(route,/proc_healthcheck_v1/)
  assert.match(route,/schema_ready/)
})

test('automation exceptions remain durable for non-routine failures',()=>{
  const urgent=read('components/modules-urgent.jsx')
  const migration=read('supabase/migrations/048_procurement_complete_hardening.sql')
  assert.match(migration,/create table if not exists public\.proc_automation_jobs/)
  assert.match(urgent,/Automation Exceptions/)
  assert.match(urgent,/proc_retry_automation_job_v1/)
  assert.match(urgent,/rfq_reminder/)
  assert.match(urgent,/po_delivery_overdue/)
  assert.match(migration,/proc_automation_sweep_v1/)
})


test('password changes enforce the hardened free-plan fallback policy',()=>{
  const auth=read('components/auth-screen.jsx')
  assert.match(auth,/function passwordIssue\(value\)/)
  assert.match(auth,/value\.length<12/)
  assert.match(auth,/\!\/\[a-z\]\//)
  assert.match(auth,/\!\/\[A-Z\]\//)
  assert.match(auth,/\!\/\[0-9\]\//)
  assert.match(auth,/\!\/\[\^A-Za-z0-9\]\//)
  assert.match(auth,/Enter your current password\./)
  assert.match(auth,/12\+ with upper\/lowercase, number & symbol/)
})


test('production runtime is pinned to Node 24',()=>{
  const pkg=JSON.parse(read('package.json'))
  assert.equal(pkg.engines?.node,'24.x')
})


test('dependency install scripts are explicitly denied and unreviewed scripts fail closed',()=>{
  const pkg=JSON.parse(read('package.json'))
  const npmrc=read('.npmrc')
  assert.equal(pkg.allowScripts?.['tesseract.js'],false)
  assert.equal(pkg.allowScripts?.['core-js'],false)
  assert.match(npmrc,/^strict-allow-scripts=true\s*$/)
})


test('WhatsApp links normalize Sri Lankan local numbers before opening',()=>{
  const helpers=read('lib/helpers.ts')
  const buying=read('components/modules-buying.jsx')
  const docs=read('components/modules-documents.jsx')

  assert.match(helpers,/export const normalizeWhatsAppNumber/)
  assert.match(helpers,/digits\.startsWith\('0'\).*countryCode \+ digits\.slice\(1\)/s)
  assert.match(helpers,/digits\.length === 9 && digits\.startsWith\('7'\)/)
  assert.match(helpers,/export const whatsappUrl/)
  assert.match(helpers,/https:\/\/wa\.me\/\$\{number\}/)

  assert.match(buying,/whatsappUrl\(s\.whatsapp\)/)
  assert.match(buying,/whatsappUrl\(s\.whatsapp\|\|s\.phone,msg\)/)
  assert.match(docs,/whatsappUrl\(active\?\.supplier\?\.whatsapp,/)

  assert.doesNotMatch(buying,/https:\/\/wa\.me\/.*replace\(\/\\D\/g/)
  assert.doesNotMatch(docs,/https:\/\/wa\.me\/.*replace\(\/\\D\/g/)
})


test('RFQ sharing offers reply-ready text, PNG sharing and aligned supplier quote outputs',()=>{
  const buying=read('components/modules-buying.jsx')
  const share=read('lib/rfq-share.js')
  const pdf=read('lib/pdf.js')

  assert.match(buying,/1 · Download PNG for WhatsApp/)
  assert.match(buying,/2 · Open WhatsApp \+ Text/)
  assert.match(buying,/Copy PNG Caption/)
  assert.match(buying,/Open Supplier Chat for Caption/)
  assert.match(buying,/WhatsApp Text/)
  assert.match(buying,/Download PNG/)
  assert.match(buying,/Copy Reply Text/)
  assert.match(buying,/buildSupplierPngShareText/)
  assert.match(buying,/prepareBrowserRfq/)
  assert.match(buying,/downloadSupplierPriceRequestPng/)
  assert.match(buying,/buildSupplierQuoteReplyText/)

  assert.match(share,/export function buildSupplierQuoteReplyText/)
  assert.match(share,/Rate: Rs\. ______/)
  assert.match(share,/Optional size variations: ______/)
  assert.match(share,/Remarks \(if needed\): ______/)
  assert.doesNotMatch(share,/Payment Terms: ______/)
  assert.match(share,/export async function createSupplierPriceRequestPng/)
  assert.match(share,/label:'QTY'/)
  assert.match(share,/label:'UNIT RATE'/)
  assert.match(share,/navigator\.share/)
  assert.match(share,/downloadSupplierPriceRequestPng/)

  assert.match(pdf,/label:'Qty'/)
  assert.match(pdf,/label:'Item \/ Size'/)
  assert.match(pdf,/label:'Unit Rate'/)
})


test('RFQ browser sharing downloads PNG before opening a specific supplier chat, with no APK',()=>{
 const buying=read('components/modules-buying.jsx')
 assert.match(buying,/async function prepareBrowserRfq\(inv\)/)
 assert.match(buying,/downloadSupplierPriceRequestPng\(supplierRequestArgs\(inv\)\)/)
 assert.match(buying,/setBrowserRfqReady\(\{invitationId:inv.id,number,filename:out.filename\}\)/)
 assert.match(buying,/function browserSupplierWhatsappUrl\(inv,withText=true\)/)
 assert.match(buying,/whatsappUrl\(s.whatsapp\|\|s.phone,withText\?buildSupplierPngShareText/)
 assert.match(buying,/browserRfqReady\?\.invitationId===x.id/)
 assert.match(buying,/Copy PNG Caption/)
 assert.match(buying,/navigator.clipboard.writeText\(buildSupplierPngShareText/)
 assert.match(buying,/Check WhatsApp before confirming Sent/)
 assert.doesNotMatch(buying,/GHProcurementAndroid/)
})

test('supplier phone entry prefixes and stores valid Sri Lankan +94 numbers',()=>{
  const ts = require('typescript')
  const moduleSource = read('lib/helpers.ts')
  const moduleObj = {exports:{}}
  const code = ts.transpileModule(moduleSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText
  new Function('module','exports',code)(moduleObj,moduleObj.exports)
  const {formatSriLankaSupplierPhoneInput:input,toSriLankaSupplierPhone:save,whatsappUrl}=moduleObj.exports
  assert.equal(input(''),'+94')
  assert.equal(input('+94'),'+94')
  assert.equal(input('0771234567'),'+94771234567')
  assert.equal(input('771234567'),'+94771234567')
  assert.equal(input('+94 077 123 4567'),'+94771234567')
  assert.equal(input('0094771234567'),'+94771234567')
  assert.equal(input('+94771234567'),'+94771234567')
  assert.equal(save('0771234567'),'+94771234567')
  assert.equal(save('771234567'),'+94771234567')
  assert.equal(save('+94771234567'),'+94771234567')
  assert.equal(save('+940771234567'),'+94771234567')
  assert.equal(save('+94'),'')
  assert.equal(save('07712'),'')
  assert.equal(save('+966556094835'),'')
  assert.equal(save('not a number'),'')
  assert.equal(whatsappUrl(save('0771234567')),'https://wa.me/94771234567')

  const buying=read('components/modules-buying.jsx')
  assert.match(buying,/phone:'\+94',whatsapp:'\+94'/)
  assert.match(buying,/formatSriLankaSupplierPhoneInput\(value\)/)
  assert.match(buying,/toSriLankaSupplierPhone\(form\.phone\)/)
  assert.match(buying,/toSriLankaSupplierPhone\(form\.whatsapp\)/)
  assert.match(buying,/phone:phone\|\|null,whatsapp:whatsapp\|\|phone\|\|null/)
  assert.match(buying,/Supplier WhatsApp must be a valid Sri Lankan number starting with \+94/)
})


test('browser-only direct supplier path does not use a generic share sheet or claim auto attachment',()=>{
 const buying=read('components/modules-buying.jsx')
 const browser=buying.slice(buying.indexOf(' async function prepareBrowserRfq(inv){'),buying.indexOf(' function copyReplyText(inv){'))
 assert.match(browser,/const s=suppliers.find\(x=>x.id===inv.supplier_id\)/)
 assert.match(browser,/normalizeWhatsAppNumber\(s.whatsapp\|\|s.phone\)/)
 assert.match(browser,/downloadSupplierPriceRequestPng/)
 assert.match(browser,/buildSupplierPngShareText/)
 assert.doesNotMatch(browser,/navigator\.share\(/)
 assert.doesNotMatch(browser,/shareRfqToSupplier/)
 assert.doesNotMatch(browser,/window\.open\(/)
 assert.match(buying,/attach it from Downloads/)
 assert.match(buying,/target="_blank" rel="noopener noreferrer"/)
})

test('supplier quotation accepts only prices plus optional remarks and alternative sizes',async()=>{
 const buying=read('components/modules-buying.jsx')
 const notes=await import('../lib/quote-line-notes.js')
 const saved=notes.encodeSupplierQuoteNotes({
  remarks:'Quoted brass finish',
  variants:[{size:'1 inch',price:'300',remarks:'In stock'},{size:'1.5 inch',price:'450',remarks:''}]
 })
 const decoded=notes.decodeSupplierQuoteNotes(saved)
 assert.equal(decoded.remarks,'Quoted brass finish')
 assert.equal(decoded.variants.length,2)
 assert.equal(decoded.variants[0].size,'1 inch')
 assert.equal(decoded.variants[1].price,'450')
 assert.deepEqual(notes.decodeSupplierQuoteNotes('Legacy supplier note'),{remarks:'Legacy supplier note',variants:[]})
 assert.equal(notes.encodeSupplierQuoteNotes({remarks:'',variants:[]}),null)
 assert.equal(notes.validateSupplierQuoteVariants([{size:'2 inch',price:'750'}]),true)
 assert.equal(notes.validateSupplierQuoteVariants([{size:'2 inch',price:''}]),false)
 assert.equal(notes.validateSupplierQuoteVariants([{size:'',price:'200'}]),false)
 assert.equal(notes.validateSupplierQuoteVariants([{size:'1 inch',price:'-2'}]),false)
 assert.match(buying,/notes:encodeSupplierQuoteNotes\(prices\[i.id\]\)/)
 assert.match(buying,/decodeSupplierQuoteNotes\(x.notes\)/)
 assert.match(buying,/\+ Add size variation/)
 assert.match(buying,/Unit price for /)
 assert.match(buying,/Quick price entry/)
 assert.match(buying,/Details \/ remarks \/ sizes/)
 assert.match(buying,/p_freight_total:0,p_minimum_order_value:0/)
 assert.match(buying,/discount_percent:0,tax_percent:0,moq:0,order_multiple:1/)
 const quoteEditor=buying.slice(buying.indexOf('   <div className="formgrid">\n    <div className="field"><label>{label(\'supplier\',\'Supplier\')}</label>'),buying.indexOf('   <div className="toolbar section">{canEdit&&<button className="btn primary" disabled={busy} onClick={saveQuote}'))
 for(const term of ['Discount %','Tax %','Lead Days','Freight Total','MOQ','Minimum Order Value'])assert.doesNotMatch(quoteEditor,new RegExp(term))
})

test('private WAHA payload addresses selected supplier and attaches a real PNG with caption',async()=>{
 const {normalizeSupplierChatId,verifyPng,wahaImagePayload,extractWahaMessageId}=await import('../lib/waha-rfq.js')
 assert.equal(normalizeSupplierChatId('+94 77 979 2078'),'94779792078@c.us')
 assert.equal(normalizeSupplierChatId('0779792078'),'94779792078@c.us')
 assert.equal(normalizeSupplierChatId('779792078'),'94779792078@c.us')
 assert.throws(()=>normalizeSupplierChatId('123'))
 assert.throws(()=>verifyPng('not a png'))
 const image=Buffer.alloc(32)
 Buffer.from('89504e470d0a1a0a','hex').copy(image,0)
 image.writeUInt32BE(1200,16);image.writeUInt32BE(900,20)
 assert.equal(verifyPng(image.toString('base64')).length,32)
 const message=wahaImagePayload({session:'default',phone:'0779792078',filename:'RFQ 102.png',base64:image.toString('base64'),caption:'Quote items'})
 assert.equal(message.chatId,'94779792078@c.us')
 assert.equal(message.file.mimetype,'image/png')
 assert.equal(message.file.filename,'RFQ-102.png')
 assert.equal(message.file.data,image.toString('base64'))
 assert.equal(message.caption,'Quote items')
 assert.equal(extractWahaMessageId({id:{_serialized:'abc123'}}),'abc123')
})
test('private WAHA route is authenticated, supplier-scoped, audited, and fails closed',()=>{
 const route=read('app/api/integrations/whatsapp/rfq/route.ts')
 const migration=read('supabase/migrations/050_procurement_whatsapp_rfq_gateway.sql')
 const buying=read('components/modules-buying.jsx')
 assert.match(route,/auth\.getUser\(token\)/)
 assert.match(route,/\['admin','procurement'\]\.includes\(profile\.role\)/)
 assert.match(route,/db\.from\('proc_rfq_suppliers'\)/)
 assert.match(route,/db\.from\('proc_suppliers'\)/)
 assert.match(route,/db\.rpc\('proc_whatsapp_claim_dispatch'/)
 assert.match(route,/db\.rpc\('proc_whatsapp_finish_dispatch'/)
 assert.match(route,/claimError\.code==='23505'/)
 assert.match(route,/gatewaySession\(config\)/)
 assert.match(route,/config\.base\+'\/api\/sendImage'/)
 assert.match(route,/status='unknown'/)
 assert.match(route,/status='accepted'/)
 assert.doesNotMatch(route,/proc_mark_rfq_supplier_sent_v1/)
 assert.match(route,/WAHA_SENDING_ENABLED/)
 assert.doesNotMatch(route,/SUPABASE_SERVICE_ROLE_KEY/)
 assert.match(route,/railway/)
 assert.match(migration,/unique \(rfq_id,supplier_id\)/)
 assert.match(migration,/enable row level security/)
 assert.match(migration,/revoke insert,update,delete/)
 assert.match(migration,/proc_has_permission\('procurement\.rfq\.view'\)/)
 assert.match(buying,/Send Attached PNG \+ Caption/)
 assert.match(buying,/createSupplierPriceRequestPng\(supplierRequestArgs\(inv\)\)/)
 assert.match(buying,/Authorization:'Bearer '\+session\.access_token/)
 assert.match(buying,/browserSupplierWhatsappUrl/)
 assert.match(buying,/Check WhatsApp before confirming Sent/)
})


test('WAHA session pairing uses a private admin-only proxy and leaves sending disabled',()=>{
 const pairing=read('app/api/integrations/whatsapp/pair/route.ts')
 const send=read('app/api/integrations/whatsapp/rfq/route.ts')
 const buying=read('components/modules-buying.jsx')
 assert.match(pairing,/auth\.getUser\(match\[1\]\)/)
 assert.match(pairing,/profile\?\.role!=='admin'/)
 assert.match(pairing,/url\.hostname\.endsWith\('\.railway\.internal'\)/)
 assert.match(pairing,/\/api\/sessions/)
 assert.match(pairing,/\/auth\/request-code/)
 assert.match(pairing,/\/auth\/qr\?format=image/)
 assert.match(pairing,/signal:AbortSignal\.timeout/)
 assert.doesNotMatch(pairing,/NEXT_PUBLIC_WAHA_API_KEY/)
 assert.match(send,/WAHA_SENDING_ENABLED!=='true'/)
 assert.match(send,/sendingEnabled:process\.env\.WAHA_SENDING_ENABLED==='true'/)
 assert.match(buying,/WhatsApp Gateway Setup \(Administrator\)/)
 assert.match(buying,/Request Pairing Code/)
 assert.match(buying,/Refresh Pairing Status/)
 assert.match(buying,/!gateway\.sendingEnabled/)
 assert.doesNotMatch(buying,/window\.GHProcurementAndroid/)
})
