import {purchaseOrderShareModel} from './po-share.js'
import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'

const safe = v => v === null || v === undefined ? '' : String(v)

function addHeader(doc,{title,subtitle,company}){
  const name=company?.name||'General Hardware'
  doc.setFont('helvetica','bold'); doc.setFontSize(17); doc.text(name,14,16)
  doc.setFont('helvetica','normal'); doc.setFontSize(9)
  const companyLine=[company?.town,company?.country].filter(Boolean).join(' · ')
  if(companyLine)doc.text(companyLine,14,22)
  if(company?.phone||company?.email)doc.text([company?.phone,company?.email].filter(Boolean).join(' · '),14,27)
  doc.setFont('helvetica','bold'); doc.setFontSize(14); doc.text(title,doc.internal.pageSize.getWidth()-14,16,{align:'right'})
  doc.setFont('helvetica','normal'); doc.setFontSize(9)
  if(subtitle)doc.text(subtitle,doc.internal.pageSize.getWidth()-14,22,{align:'right'})
  doc.setDrawColor(180); doc.line(14,32,doc.internal.pageSize.getWidth()-14,32)
  return 38
}

function addFooter(doc,footer){
  const pages=doc.getNumberOfPages()
  for(let i=1;i<=pages;i++){
    doc.setPage(i)
    doc.setFontSize(8); doc.setTextColor(110)
    doc.text(footer||'Generated by GH Procurement',14,doc.internal.pageSize.getHeight()-8)
    doc.text(`Page ${i} of ${pages}`,doc.internal.pageSize.getWidth()-14,doc.internal.pageSize.getHeight()-8,{align:'right'})
    doc.setTextColor(0)
  }
}

export function exportTablePdf({filename,title,subtitle,columns,rows,company,footer,orientation='landscape'}){
  const doc=new jsPDF({orientation,unit:'mm',format:'a4'})
  const startY=addHeader(doc,{title,subtitle,company})
  autoTable(doc,{
    startY,
    head:[columns.map(c=>safe(c.label||c.key))],
    body:rows.map(r=>columns.map(c=>safe(typeof c.value==='function'?c.value(r):r[c.key]))),
    styles:{fontSize:7.5,cellPadding:2,overflow:'linebreak'},
    headStyles:{fillColor:[31,41,55],textColor:255,fontStyle:'bold'},
    alternateRowStyles:{fillColor:[248,250,252]},
    margin:{left:10,right:10,bottom:16},
    didDrawPage:()=>{}
  })
  addFooter(doc,footer)
  doc.save(filename)
}

export function exportSupplierPriceRequestPdf({rfq,items,supplier,company,footer}){
  const supplierName=supplier?.name||'Supplier'
  const clean=v=>String(v||'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'')
  exportTablePdf({
    filename:`${clean(rfq?.rfq_no||'RFQ')}-${clean(supplierName)||'supplier'}.pdf`,
    title:'REQUEST FOR QUOTATION',
    subtitle:[rfq?.rfq_no,supplierName,rfq?.due_date?'Reply by '+rfq.due_date:null].filter(Boolean).join(' · '),
    company,footer,orientation:'portrait',
    columns:[
      {key:'no',label:'#',value:r=>r.no},
      {key:'qty',label:'Qty',value:r=>r.qty},
      {key:'uom',label:'UOM',value:r=>r.uom},
      {key:'item',label:'Item / Size',value:r=>r.item},
      {key:'price',label:'Unit Rate',value:()=>''},
      {key:'available',label:'Available',value:()=>''},
      {key:'lead',label:'Delivery / Lead Time',value:()=>''}
    ],
    rows:(items||[]).map((x,index)=>{
      const item=x.requirement?.item||x.item||{}
      return {
        no:index+1,
        item:[item.description,item.size].filter(Boolean).join(' · '),
        uom:item.uom||'',
        qty:x.requested_qty??x.qty??''
      }
    })
  })
}

export function exportPurchaseOrderPdf({po,lines,company,footer,selection}){
  const m=purchaseOrderShareModel({po,lines,company,selection})
  const doc=new jsPDF({orientation:m.columns.length>6?'landscape':'portrait',unit:'mm',format:'a4'})
  let y=addHeader(doc,{title:'PURCHASE ORDER',subtitle:po.po_no,company})
  doc.setFontSize(9)
  for(const [k,v] of m.meta){
    const wrapped=doc.splitTextToSize(v,doc.internal.pageSize.getWidth()-65)
    doc.setFont('helvetica','bold');doc.text(k,14,y)
    doc.setFont('helvetica','normal');doc.text(wrapped,48,y)
    y+=Math.max(6,wrapped.length*5)
  }
  autoTable(doc,{startY:y+2,head:[m.columns.map(c=>c.label)],body:m.rows,
    styles:{fontSize:8,cellPadding:2,overflow:'linebreak'},headStyles:{fillColor:[31,41,55],textColor:255},margin:{left:14,right:14,bottom:30}})
  if(m.total){let fy=(doc.lastAutoTable?.finalY||y)+8;if(fy>doc.internal.pageSize.getHeight()-32){doc.addPage();fy=20}
    doc.setFont('helvetica','bold');doc.text('TOTAL: '+m.total,doc.internal.pageSize.getWidth()-14,fy,{align:'right'})}
  for(let page=1;page<=doc.getNumberOfPages();page++){doc.setPage(page);addStockApprovalFooter(doc)}
  addFooter(doc,footer)
  doc.save(`${String(po.po_no||'Purchase-Order').replace(/[^a-zA-Z0-9_-]/g,'-')}.pdf`)
}

function addStockApprovalFooter(doc){
  const pageW=doc.internal.pageSize.getWidth()
  const pageH=doc.internal.pageSize.getHeight()
  const y=pageH-18
  const left=12
  const right=pageW-12
  const gap=4
  const dateW=28
  const sigW=(right-left-dateW-gap*3)/3
  const fields=[
    ['Stocks Checked By',sigW],
    ['Stocks Verified By',sigW],
    ['Order Approved By',sigW],
    ['Date',dateW],
  ]
  let x=left
  doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(70)
  for(const [label,w] of fields){
    doc.setDrawColor(150);doc.line(x,y,x+w,y)
    doc.text(label,x+w/2,y+4,{align:'center'})
    x+=w+gap
  }
  doc.setTextColor(0)
}

function stockPageHeader(doc,{company,title,subtitle,pageNo,totalPages}){
  const pageW=doc.internal.pageSize.getWidth()
  const name=company?.name||'General Hardware'
  doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(name,12,12)
  doc.setFont('helvetica','normal');doc.setFontSize(7.5)
  doc.text([company?.town,company?.country].filter(Boolean).join(' · '),12,17)
  doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(title,pageW-12,12,{align:'right'})
  doc.setFont('helvetica','normal');doc.setFontSize(7.5)
  if(subtitle)doc.text(subtitle,pageW-12,17,{align:'right'})
  doc.text(`Page ${pageNo} of ${totalPages}`,pageW-12,22,{align:'right'})
  doc.setDrawColor(170);doc.line(12,25,pageW-12,25)
}

function exportThreeTableStockPdf({filename,title,subtitle,company,items,columns,rowBuilder,rowsPerTable=10,tablesPerPage=3}){
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'})
  tablesPerPage=Math.max(1,Math.min(Number(tablesPerPage)||3,4))
  rowsPerTable=Math.max(5,Math.min(Number(rowsPerTable)||10,25))
  const perPage=rowsPerTable*tablesPerPage
  const totalPages=Math.max(1,Math.ceil(items.length/perPage))
  const starts=tablesPerPage===3?[30,105,180]:Array.from({length:tablesPerPage},(_,i)=>30+i*((250-30)/tablesPerPage))

  for(let p=0;p<totalPages;p++){
    if(p>0)doc.addPage()
    stockPageHeader(doc,{company,title,subtitle,pageNo:p+1,totalPages})
    const pageItems=items.slice(p*perPage,(p+1)*perPage)

    for(let t=0;t<tablesPerPage;t++){
      const chunk=pageItems.slice(t*rowsPerTable,(t+1)*rowsPerTable)
      const padded=[...chunk]
      while(padded.length<rowsPerTable)padded.push(null)
      autoTable(doc,{
        startY:starts[t],
        head:[columns.map(c=>c.label)],
        body:padded.map((item,idx)=>item?rowBuilder(item,p*perPage+t*rowsPerTable+idx+1):columns.map(()=>'')),
        theme:'grid',
        styles:{fontSize:7.4,cellPadding:1.4,minCellHeight:5.3,overflow:'linebreak',valign:'middle'},
        headStyles:{fillColor:[31,41,55],textColor:255,fontStyle:'bold',minCellHeight:5.5},
        margin:{left:12,right:12},
        tableWidth:'auto',
        pageBreak:'avoid',
        rowPageBreak:'avoid'
      })
    }
    addStockApprovalFooter(doc)
  }
  doc.save(filename)
}

export function exportMovementChecklistPdf({items,company,movement='FAST',category='',title='STOCK CHECKLIST',templateConfig={}}){
  const filtered=items.filter(i=>(!movement||i.movement===movement)&&(!category||i.category===category))
  const showCode=templateConfig.show_code===true
  const showUom=templateConfig.show_uom===true
  const showMovement=templateConfig.show_movement===true
  const defs=[
    {key:'no',label:'No.',get:(i,n)=>String(n)},
    ...(showCode?[{key:'code',label:'Code',get:i=>safe(i.item_code)}]:[]),
    {key:'description',label:'Description',get:i=>safe(i.description)},
    {key:'size',label:'Size',get:i=>safe(i.size)},
    ...(showUom?[{key:'uom',label:'UOM',get:i=>safe(i.uom)}]:[]),
    ...(showMovement?[{key:'movement',label:'Movement',get:i=>safe(i.movement)}]:[]),
    {key:'max',label:'Max Stock',get:i=>safe(i.max_stock)},
    {key:'reorder',label:'Reorder Level',get:i=>safe(i.reorder_level)},
    {key:'order',label:'Order',get:()=>''},
  ]
  exportThreeTableStockPdf({
    filename:`GH-${movement||'All'}-Stock-Checklist.pdf`,
    title:`${movement||'ALL'} MOVING STOCK CHECKLIST`,
    subtitle:[category||'All Categories',`${filtered.length} items`].join(' · '),
    company,
    items:filtered,
    rowsPerTable:templateConfig.rows_per_table??10,
    tablesPerPage:templateConfig.tables_per_page??3,
    columns:defs.map(x=>({label:x.label})),
    rowBuilder:(i,n)=>defs.map(x=>x.get(i,n))
  })
}

export function exportStockSheetPdf({items,company,footer,fields=[],title='STOCK CHECK SHEET',stockTaking=false,subtitle=''}) {
  if(stockTaking){
    exportThreeTableStockPdf({
      filename:'GH-Stock-Taking-Sheet.pdf',
      title:'STOCK TAKING SHEET',
      subtitle,
      company,
      items,
      rowsPerTable:10,
      columns:[
        {label:'Description'},
        {label:'Current Stock'},
        {label:'Book Stock'},
        {label:'Variance'},
      ],
      rowBuilder:i=>[
        safe([i.description,i.size].filter(Boolean).join(' · ')),
        '',
        safe(i.book_stock??''),
        ''
      ]
    })
    return
  }

  const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'})
  const startY=addHeader(doc,{title,subtitle,company})
  const cfg=key=>fields.find(f=>f.module_key==='stock'&&f.field_key===key)
  const show=key=>cfg(key)?cfg(key).enabled!==false:true
  const label=(key,fallback)=>cfg(key)?.label||fallback
  const stockDefs=[
    ['item_code','Code',i=>i.item_code],
    ['description','Description',i=>i.description],
    ['main_group','Main Group',i=>i.main_group],
    ['subgroup','Subgroup',i=>i.subgroup],
    ['size','Size',i=>i.size],
    ['uom','UOM',i=>i.uom],
    ['movement','Movement',i=>i.movement],
    ['max_stock','Max Stock',i=>i.max_stock],
    ['reorder_level','Reorder At',i=>i.reorder_level],
    ['current_stock','Current Stock',()=> ''],
    ['remarks','Remarks',i=>i.remarks],
  ].filter(([key])=>show(key))

  autoTable(doc,{
    startY,
    head:[stockDefs.map(([key,fallback])=>label(key,fallback))],
    body:items.map(i=>stockDefs.map(([, ,getter])=>safe(getter(i)))),
    styles:{fontSize:7.2,cellPadding:2.1,minCellHeight:7},
    headStyles:{fillColor:[31,41,55],textColor:255},
    alternateRowStyles:{fillColor:[248,250,252]},
    margin:{left:10,right:10,bottom:20}
  })
  addFooter(doc,footer)
  doc.save('GH-Stock-Check-Sheet.pdf')
}
