import { jsPDF } from 'jspdf'
import { autoTable } from 'jspdf-autotable'

const safe = v => v === null || v === undefined ? '' : String(v)

function addHeader(doc,{title,subtitle,company}){
  const name=company?.name||'General Hardware'
  doc.setFont('helvetica','bold'); doc.setFontSize(17); doc.text(name,14,16)
  doc.setFont('helvetica','normal'); doc.setFontSize(9)
  const companyLine=[company?.town,company?.country].filter(Boolean).join(' · ')
  if(companyLine)doc.text(companyLine,14,22)
  if(company?.phone||company?.email)doc.text([company?.phone,company?.email].filter(Boolean).join(' · '),14,27)
  doc.setFont('helvetica','bold'); doc.setFontSize(14); doc.text(title,doc.internal.pageSize.getWidth()-14,16,{align:'right'})
  doc.setFont('helvetica','normal'); doc.setFontSize(9)
  if(subtitle)doc.text(subtitle,doc.internal.pageSize.getWidth()-14,22,{align:'right'})
  doc.setDrawColor(180); doc.line(14,32,doc.internal.pageSize.getWidth()-14,32)
  return 38
}

function addFooter(doc,footer){
  const pages=doc.getNumberOfPages()
  for(let i=1;i<=pages;i++){
    doc.setPage(i)
    doc.setFontSize(8); doc.setTextColor(110)
    doc.text(footer||'Generated by GH Procurement',14,doc.internal.pageSize.getHeight()-8)
    doc.text(`Page ${i} of ${pages}`,doc.internal.pageSize.getWidth()-14,doc.internal.pageSize.getHeight()-8,{align:'right'})
    doc.setTextColor(0)
  }
}

export function exportTablePdf({filename,title,subtitle,columns,rows,company,footer,orientation='landscape'}){
  const doc=new jsPDF({orientation,unit:'mm',format:'a4'})
  const startY=addHeader(doc,{title,subtitle,company})
  autoTable(doc,{
    startY,
    head:[columns.map(c=>safe(c.label||c.key))],
    body:rows.map(r=>columns.map(c=>safe(typeof c.value==='function'?c.value(r):r[c.key]))),
    styles:{fontSize:7.5,cellPadding:2,overflow:'linebreak'},
    headStyles:{fillColor:[31,41,55],textColor:255,fontStyle:'bold'},
    alternateRowStyles:{fillColor:[248,250,252]},
    margin:{left:10,right:10,bottom:16},
    didDrawPage:()=>{}
  })
  addFooter(doc,footer)
  doc.save(filename)
}

export function exportSupplierPriceRequestPdf({rfq,items,supplier,company,footer}){
  const supplierName=supplier?.name||'Supplier'
  const clean=v=>String(v||'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-|-$/g,'')
  exportTablePdf({
    filename:`${clean(rfq?.rfq_no||'RFQ')}-${clean(supplierName)||'supplier'}.pdf`,
    title:'REQUEST FOR QUOTATION',
    subtitle:[rfq?.rfq_no,supplierName,rfq?.due_date?'Reply by '+rfq.due_date:null].filter(Boolean).join(' · '),
    company,footer,orientation:'portrait',
    columns:[
      {key:'no',label:'#',value:r=>r.no},
      {key:'qty',label:'Qty',value:r=>r.qty},
      {key:'uom',label:'UOM',value:r=>r.uom},
      {key:'item',label:'Item / Size',value:r=>r.item},
      {key:'price',label:'Unit Rate',value:()=>''},
      {key:'available',label:'Available',value:()=>''},
      {key:'lead',label:'Delivery / Lead Time',value:()=>''}
    ],
    rows:(items||[]).map((x,index)=>{
      const item=x.requirement?.item||x.item||{}
      return {
        no:index+1,
        item:[item.description,item.size].filter(Boolean).join(' · '),
        uom:item.uom||'',
        qty:x.requested_qty??x.qty??''
      }
    })
  })
}

export function exportPurchaseOrderPdf({po,lines,company,footer,fields=[]}){
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'})
  const cfg=key=>fields.find(f=>f.module_key==='po'&&f.field_key===key)
  const show=key=>cfg(key)?cfg(key).enabled!==false:true
  const label=(key,fallback)=>cfg(key)?.label||fallback
  let y=addHeader(doc,{title:'PURCHASE ORDER',subtitle:po.po_no,company})
  doc.setFontSize(9)

  const meta=[]
  if(show('supplier'))meta.push([label('supplier','Supplier'),safe(po.supplier?.name)])
  if(show('po_date'))meta.push([label('po_date','PO Date'),safe(po.po_date)])
  if(show('expected_date'))meta.push([label('expected_date','Expected Delivery'),safe(po.expected_date||'—')])
  if(show('terms'))meta.push([label('terms','Terms'),safe(po.terms||po.supplier?.payment_terms||'—')])
  if(show('notes')&&po.notes)meta.push([label('notes','Notes'),safe(po.notes)])

  for(const [k,v] of meta){
    doc.setFont('helvetica','bold');doc.text(k,14,y)
    doc.setFont('helvetica','normal');doc.text(v,48,y,{maxWidth:145})
    y+=6
  }
  y+=2

  const defs=[
    ['item_code','Code',l=>l.item?.item_code],
    ['description','Description',l=>l.item?.description],
    ['size','Size',l=>l.item?.size],
    ['uom','UOM',l=>l.item?.uom],
    ['qty','Qty',l=>safe(l.qty)],
    ['unit_price','Unit Price',l=>Number(l.unit_price||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})],
    ['discount_percent','Discount %',l=>Number(l.discount_percent||0).toFixed(2)+'%'],
    ['tax_percent','Tax %',l=>Number(l.tax_percent||0).toFixed(2)+'%'],
    ['effective_unit_cost','Effective Unit',l=>(Number(l.unit_price||0)*(1-Number(l.discount_percent||0)/100)*(1+Number(l.tax_percent||0)/100)).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})],
    ['landed_unit_cost','Landed Unit',l=>l.landed_unit_cost==null?'—':Number(l.landed_unit_cost).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})],
    ['line_total','Line Total',l=>Number(l.line_total||0).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})],
  ].filter(([key])=>show(key))

  autoTable(doc,{
    startY:y,
    head:[defs.map(([key,fallback])=>label(key,fallback))],
    body:lines.map(l=>defs.map(([, ,getter])=>safe(getter(l)))),
    styles:{fontSize:8,cellPadding:2},
    headStyles:{fillColor:[31,41,55],textColor:255},
    margin:{left:14,right:14}
  })

  let fy=(doc.lastAutoTable?.finalY||y)+8
  if(show('total')){
    doc.setFontSize(9);doc.setFont('helvetica','bold')
    doc.text('Subtotal',142,fy,{align:'right'});doc.text(Number(po.subtotal||0).toLocaleString('en-LK',{minimumFractionDigits:2}),194,fy,{align:'right'})
    fy+=5;doc.text('Tax',142,fy,{align:'right'});doc.text(Number(po.tax_total||0).toLocaleString('en-LK',{minimumFractionDigits:2}),194,fy,{align:'right'})
    if(show('freight_total')){fy+=5;doc.text(label('freight_total','Freight'),142,fy,{align:'right'});doc.text(Number(po.freight_total||0).toLocaleString('en-LK',{minimumFractionDigits:2}),194,fy,{align:'right'})}
    fy+=6;doc.setFontSize(11);doc.text(label('total','TOTAL LKR').toUpperCase(),142,fy,{align:'right'});doc.text(Number(po.total||0).toLocaleString('en-LK',{minimumFractionDigits:2}),194,fy,{align:'right'})
  }
  const pages=doc.getNumberOfPages()
  for(let p=1;p<=pages;p++){
    doc.setPage(p)
    addStockApprovalFooter(doc)
  }
  addFooter(doc,footer)
  doc.save(`${po.po_no||'Purchase-Order'}.pdf`)
}

function addStockApprovalFooter(doc){
  const pageW=doc.internal.pageSize.getWidth()
  const pageH=doc.internal.pageSize.getHeight()
  const y=pageH-18
  const left=12
  const right=pageW-12
  const gap=4
  const dateW=28
  const sigW=(right-left-dateW-gap*3)/3
  const fields=[
    ['Stocks Checked By',sigW],
    ['Stocks Verified By',sigW],
    ['Order Approved By',sigW],
    ['Date',dateW],
  ]
  let x=left
  doc.setFont('helvetica','normal');doc.setFontSize(7.5);doc.setTextColor(70)
  for(const [label,w] of fields){
    doc.setDrawColor(150);doc.line(x,y,x+w,y)
    doc.text(label,x+w/2,y+4,{align:'center'})
    x+=w+gap
  }
  doc.setTextColor(0)
}

function stockPageHeader(doc,{company,title,subtitle,pageNo,totalPages}){
  const pageW=doc.internal.pageSize.getWidth()
  const name=company?.name||'General Hardware'
  doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(name,12,12)
  doc.setFont('helvetica','normal');doc.setFontSize(7.5)
  doc.text([company?.town,company?.country].filter(Boolean).join(' · '),12,17)
  doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text(title,pageW-12,12,{align:'right'})
  doc.setFont('helvetica','normal');doc.setFontSize(7.5)
  if(subtitle)doc.text(subtitle,pageW-12,17,{align:'right'})
  doc.text(`Page ${pageNo} of ${totalPages}`,pageW-12,22,{align:'right'})
  doc.setDrawColor(170);doc.line(12,25,pageW-12,25)
}

function exportThreeTableStockPdf({filename,title,subtitle,company,items,columns,rowBuilder,rowsPerTable=10,tablesPerPage=3}){
  const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4'})
  tablesPerPage=Math.max(1,Math.min(Number(tablesPerPage)||3,4))
  rowsPerTable=Math.max(5,Math.min(Number(rowsPerTable)||10,25))
  const perPage=rowsPerTable*tablesPerPage
  const totalPages=Math.max(1,Math.ceil(items.length/perPage))
  const starts=tablesPerPage===3?[30,105,180]:Array.from({length:tablesPerPage},(_,i)=>30+i*((250-30)/tablesPerPage))

  for(let p=0;p<totalPages;p++){
    if(p>0)doc.addPage()
    stockPageHeader(doc,{company,title,subtitle,pageNo:p+1,totalPages})
    const pageItems=items.slice(p*perPage,(p+1)*perPage)

    for(let t=0;t<tablesPerPage;t++){
      const chunk=pageItems.slice(t*rowsPerTable,(t+1)*rowsPerTable)
      const padded=[...chunk]
      while(padded.length<rowsPerTable)padded.push(null)
      autoTable(doc,{
        startY:starts[t],
        head:[columns.map(c=>c.label)],
        body:padded.map((item,idx)=>item?rowBuilder(item,p*perPage+t*rowsPerTable+idx+1):columns.map(()=>'')),
        theme:'grid',
        styles:{fontSize:7.4,cellPadding:1.4,minCellHeight:5.3,overflow:'linebreak',valign:'middle'},
        headStyles:{fillColor:[31,41,55],textColor:255,fontStyle:'bold',minCellHeight:5.5},
        margin:{left:12,right:12},
        tableWidth:'auto',
        pageBreak:'avoid',
        rowPageBreak:'avoid'
      })
    }
    addStockApprovalFooter(doc)
  }
  doc.save(filename)
}

export function exportMovementChecklistPdf({items,company,movement='FAST',category='',title='STOCK CHECKLIST',templateConfig={}}){
  const filtered=items.filter(i=>(!movement||i.movement===movement)&&(!category||i.category===category))
  const showCode=templateConfig.show_code===true
  const showUom=templateConfig.show_uom===true
  const showMovement=templateConfig.show_movement===true
  const defs=[
    {key:'no',label:'No.',get:(i,n)=>String(n)},
    ...(showCode?[{key:'code',label:'Code',get:i=>safe(i.item_code)}]:[]),
    {key:'description',label:'Description',get:i=>safe(i.description)},
    {key:'size',label:'Size',get:i=>safe(i.size)},
    ...(showUom?[{key:'uom',label:'UOM',get:i=>safe(i.uom)}]:[]),
    ...(showMovement?[{key:'movement',label:'Movement',get:i=>safe(i.movement)}]:[]),
    {key:'max',label:'Max Stock',get:i=>safe(i.max_stock)},
    {key:'reorder',label:'Reorder Level',get:i=>safe(i.reorder_level)},
    {key:'order',label:'Order',get:()=>''},
  ]
  exportThreeTableStockPdf({
    filename:`GH-${movement||'All'}-Stock-Checklist.pdf`,
    title:`${movement||'ALL'} MOVING STOCK CHECKLIST`,
    subtitle:[category||'All Categories',`${filtered.length} items`].join(' · '),
    company,
    items:filtered,
    rowsPerTable:templateConfig.rows_per_table??10,
    tablesPerPage:templateConfig.tables_per_page??3,
    columns:defs.map(x=>({label:x.label})),
    rowBuilder:(i,n)=>defs.map(x=>x.get(i,n))
  })
}

export function exportStockSheetPdf({items,company,footer,fields=[],title='STOCK CHECK SHEET',stockTaking=false,subtitle=''}) {
  if(stockTaking){
    exportThreeTableStockPdf({
      filename:'GH-Stock-Taking-Sheet.pdf',
      title:'STOCK TAKING SHEET',
      subtitle,
      company,
      items,
      rowsPerTable:10,
      columns:[
        {label:'Description'},
        {label:'Current Stock'},
        {label:'Book Stock'},
        {label:'Variance'},
      ],
      rowBuilder:i=>[
        safe([i.description,i.size].filter(Boolean).join(' · ')),
        '',
        safe(i.book_stock??''),
        ''
      ]
    })
    return
  }

  const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'})
  const startY=addHeader(doc,{title,subtitle,company})
  const cfg=key=>fields.find(f=>f.module_key==='stock'&&f.field_key===key)
  const show=key=>cfg(key)?cfg(key).enabled!==false:true
  const label=(key,fallback)=>cfg(key)?.label||fallback
  const stockDefs=[
    ['item_code','Code',i=>i.item_code],
    ['description','Description',i=>i.description],
    ['main_group','Main Group',i=>i.main_group],
    ['subgroup','Subgroup',i=>i.subgroup],
    ['size','Size',i=>i.size],
    ['uom','UOM',i=>i.uom],
    ['movement','Movement',i=>i.movement],
    ['max_stock','Max Stock',i=>i.max_stock],
    ['reorder_level','Reorder At',i=>i.reorder_level],
    ['current_stock','Current Stock',()=> ''],
    ['remarks','Remarks',i=>i.remarks],
  ].filter(([key])=>show(key))

  autoTable(doc,{
    startY,
    head:[stockDefs.map(([key,fallback])=>label(key,fallback))],
    body:items.map(i=>stockDefs.map(([, ,getter])=>safe(getter(i)))),
    styles:{fontSize:7.2,cellPadding:2.1,minCellHeight:7},
    headStyles:{fillColor:[31,41,55],textColor:255},
    alternateRowStyles:{fillColor:[248,250,252]},
    margin:{left:10,right:10,bottom:20}
  })
  addFooter(doc,footer)
  doc.save('GH-Stock-Check-Sheet.pdf')
}
